import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import fs from "node:fs";
import http from "node:http";
import os from "node:os";
import path from "node:path";
import readline from "node:readline";
import { test } from "node:test";

const plugin = path.resolve("plugins/wmux/scripts/wmux-mcp.mjs"), hook = path.resolve("plugins/wmux/scripts/wmux-context.mjs"), config = path.resolve("plugins/wmux/.mcp.json");
const sessionId = "session_one", bindingId = "B".repeat(22), receipt = "R".repeat(43);
function fakeCodex(home: string) { const directory = fs.mkdtempSync(path.join(os.tmpdir(), "wmux-fake-codex-")); fs.writeFileSync(path.join(directory, "codex"), `#!${process.execPath}\nconst fs=require('node:fs'),path=require('node:path'),home=process.env.CODEX_HOME,state=path.join(home,'name'),log=path.join(home,'calls');function o(id,result){process.stdout.write(JSON.stringify({jsonrpc:'2.0',id,result})+'\\n')}process.stdin.on('data',d=>d.toString().split('\\n').filter(Boolean).forEach(l=>{const m=JSON.parse(l);fs.appendFileSync(log,m.method+'\\n');if(m.method==='initialize')o(m.id,{});else if(m.method==='thread/read')o(m.id,{thread:{id:m.params.threadId,name:fs.existsSync(state)?fs.readFileSync(state,'utf8'):null}});else if(m.method==='thread/name/set'){fs.writeFileSync(state,process.env.FAKE_CANONICAL||m.params.name);o(m.id,{})}}));`); fs.chmodSync(path.join(directory, "codex"), 0o755); return { directory, dispose: () => fs.rmSync(directory, { recursive: true, force: true }) }; }
function cleanEnv(home: string, fake: string) { const result = { ...process.env, HOME: home, CODEX_HOME: home, PATH: `${fake}:${process.env.PATH}` }; for (const key of Object.keys(result)) if (key.startsWith("WMUX_")) delete result[key]; return result; }
async function server(handler: http.RequestListener) { const value = http.createServer(handler); await new Promise<void>(resolve => value.listen(0, "127.0.0.1", resolve)); const address = value.address(); assert.ok(address && typeof address !== "string"); return { value, url: `http://127.0.0.1:${address.port}` }; }
function wire(home: string, url: string) { fs.mkdirSync(path.join(home, ".wmux"), { recursive: true, mode: 0o700 }); fs.writeFileSync(path.join(home, ".wmux", "url"), url); fs.writeFileSync(path.join(home, ".wmux", "helper-token"), "a".repeat(32), { mode: 0o600 }); }
function mcp(environment: NodeJS.ProcessEnv) { const child = spawn(process.execPath, [plugin], { env: environment, stdio: ["pipe", "pipe", "pipe"] }); const pending = new Map<number, (v: any) => void>(); readline.createInterface({ input: child.stdout }).on("line", line => { const message = JSON.parse(line); pending.get(message.id)?.(message); pending.delete(message.id); }); let id = 0; return { child, request(method: string, params = {}) { return new Promise<any>(resolve => { const requestId = ++id; pending.set(requestId, resolve); child.stdin.write(`${JSON.stringify({ jsonrpc: "2.0", id: requestId, method, params })}\n`); }); } }; }
async function runHook(environment: NodeJS.ProcessEnv) { return new Promise<any>((resolve, reject) => { const child = spawn(process.execPath, [hook], { env: environment, stdio: ["pipe", "pipe", "pipe"] }); let output = "", error = ""; child.stdout.on("data", chunk => output += chunk); child.stderr.on("data", chunk => error += chunk); child.once("exit", code => code === 0 ? resolve(JSON.parse(output || "{}")) : reject(new Error(error))); child.stdin.end(JSON.stringify({ hook_event_name: "UserPromptSubmit", session_id: sessionId, prompt: "private prompt" })); }); }
function json(response: http.ServerResponse, body: object, status = 200) { response.writeHead(status, { "content-type": "application/json" }).end(JSON.stringify(body)); }

test("plugin MCP supports private wmux connection files and optional embedded credentials", () => { const parsed = JSON.parse(fs.readFileSync(config, "utf8")); assert.ok(parsed.mcpServers.wmux.env_vars.includes("CODEX_HOME")); assert.ok(parsed.mcpServers.wmux.env_vars.includes("WMUX_HELPER_TOKEN_PATH")); assert.equal(parsed.mcpServers.wmux.env_vars.includes("WMUX_WORKSPACE_ID"), false); });

test("issue marker keeps receipt private; explicit binding reads, saves canonical Codex name, then mirrors", async () => {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), "wmux-plugin-")), fake = fakeCodex(home); let title: any;
  const fixture = await server(async (request, response) => { let body = ""; for await (const chunk of request) body += chunk; const parsed = body ? JSON.parse(body) : {}; assert.equal(request.headers.authorization, `Bearer ${"a".repeat(32)}`); if (request.url === "/api/codex-bindings") return json(response, { receipt, marker: `[[WMUX:${bindingId}]]`, expiresAt: "2030-01-01T00:00:00.000Z" }); if (request.url === "/api/codex-bindings/resolve") { assert.deepEqual(parsed, { sessionId, receipt }); return json(response, { workspaceId: "workspace", tabId: "tab", paneId: "pane", sessionId, expiresAt: "2030-01-01T00:00:00.000Z" }); } if (request.url === "/api/codex-bindings/title") { title = parsed; return json(response, { sessionId, workspaceId: "workspace", tabId: "tab", paneId: "pane", workspace: { id: "workspace", name: "User title", nameSource: "manual", tabs: [{ id: "tab", title: "User tab", titleSource: "manual", panes: [{ id: "pane" }] }] }, workspaceApplied: false, tabApplied: false }); } return json(response, {}, 404); });
  wire(home, fixture.url); const environment = cleanEnv(home, fake.directory); try { const output = await runHook(environment); assert.equal(output.systemMessage, `[[WMUX:${bindingId}]]`); assert.match(output.hookSpecificOutput.additionalContext, new RegExp(`sessionId=${sessionId} bindingId=${bindingId}`)); assert.doesNotMatch(JSON.stringify(output), new RegExp(receipt)); const files = fs.readdirSync(path.join(home, ".wmux", "codex-plugin")); assert.equal(files.length, 1); assert.equal(JSON.parse(fs.readFileSync(path.join(home, ".wmux", "codex-plugin", files[0]), "utf8")).receipt, receipt); const client = mcp({ ...environment, FAKE_CANONICAL: "Canonical" }); try { const named = await client.request("tools/call", { name: "name_current_wmux_session", arguments: { sessionId, bindingId, title: "Semantic task" } }); assert.equal(named.result.structuredContent.codexName, "Canonical"); assert.equal(named.result.structuredContent.codexNameSet, true); assert.equal(named.result.structuredContent.workspaceApplied, false); assert.equal(title.title, "Canonical"); assert.equal(title.receipt, receipt); assert.deepEqual(fs.readFileSync(path.join(home, "calls"), "utf8").trim().split("\n"), ["initialize", "initialized", "thread/read", "thread/name/set", "thread/read"]); } finally { client.child.kill(); } } finally { fixture.value.close(); fake.dispose(); fs.rmSync(home, { recursive: true, force: true }); }
});

test("stale bindings fail before Codex naming and manual protection is reported from wmux", async () => {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), "wmux-stale-")), fake = fakeCodex(home); let resolveCalls = 0;
  const fixture = await server((request, response) => { if (request.url === "/api/codex-bindings") return json(response, { receipt, marker: `[[WMUX:${bindingId}]]`, expiresAt: "2030-01-01T00:00:00.000Z" }); if (request.url === "/api/codex-bindings/resolve") { resolveCalls++; return json(response, { code: "binding_pending" }, 409); } return json(response, {}, 500); }); wire(home, fixture.url); const environment = cleanEnv(home, fake.directory); try { await runHook(environment); const client = mcp(environment); try { const named = await client.request("tools/call", { name: "name_current_wmux_session", arguments: { sessionId, bindingId, title: "No stale name" } }); assert.equal(named.result.isError, true); assert.match(named.result.structuredContent.error, /stale or pending/); assert.equal(resolveCalls, 1); assert.equal(fs.existsSync(path.join(home, "calls")), false); } finally { client.child.kill(); } } finally { fixture.value.close(); fake.dispose(); fs.rmSync(home, { recursive: true, force: true }); }
});

test("a configured empty helper file never falls back to the broad token", async () => {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), "wmux-helper-")), fake = fakeCodex(home); let calls = 0;
  const fixture = await server((_request, response) => { calls++; json(response, {}); });
  wire(home, fixture.url); fs.writeFileSync(path.join(home, ".wmux", "helper-token"), "", { mode: 0o600 }); fs.writeFileSync(path.join(home, ".wmux", "token"), "b".repeat(32), { mode: 0o600 });
  try { const output = await runHook(cleanEnv(home, fake.directory)); assert.match(output.systemMessage, /unavailable/); assert.equal(calls, 0); }
  finally { fixture.value.close(); fake.dispose(); fs.rmSync(home, { recursive: true, force: true }); }
});
